### PR TITLE
Fixed a couple things and would like to discuss a possible improvement

### PR DESCRIPTION
**Pull request by ddotthomas**
I fixed a couple mistakes I noticed here and there while working on the GUI.

 However, I would like other's opinion on whether 'sudo' should be used in the instructions. It should make it easier to install but I can also see how Steam Deck and possibly other immutable OS users might find the non sudo version easier. I changed the installer one liners to have sudo again but now they're actually in default PATH directory without having to modify .bashrc

### CODE REVIEW

**Comment by ddotthomas** [comment]
Also I unintentionally made this pull request from my main branch instead of a fixes branch so it cluttered the PR with useless commits. Also I noticed one of the things I fixed was already noticed and corrected. All that being said I'm okay with just closing and not merging this.

**Review by auyer — APPROVED** [review]

**Comment by auyer** [comment]
Hi ! Sorry for the delay. Its been a very intense month for me at work.
Don't worry about the commits. We can squash them tidy.

Thanks a lot for taking a shot a the GUI! I haven't had time to do it at all. To be honest, I was even thinking of using [EGUI](https://github.com/emilk/egui) instead of Iced. Mostly because of documentation and ease of use. But if you are able to get the GUI started with Iced, I can totally stand behind it.

One other thing I was thinking, is how its going to look in the Steam Deck UI. I don't own one (not available in my region), but I think it should be a focus.

About `sudo`, I agree its undesirable, but it makes it a lot easier for new users. I guess experienced users can work around it.

**Comment by ddotthomas** [comment]
Well, there's actually an issue with Iced applications it seems while on the Steam deck where the resolution is terrible in desktop mode and the mouse doesn't work all the way in gaming. I talk about it a little bit in my app's description https://github.com/ddotthomas/SteamDeck_SD_Card_Scanner but I made a Reddit post that has some screenshots and explains the bug a bit better https://www.reddit.com/r/SteamDeck/comments/10jk36q/having_issues_with_the_windows_size_while/

**Comment by auyer** [comment]
Wow this is indeed weird. Maybe you cloud discuss this in the Iced official Discord server?

**Pull request merged**
