### PR TITLE
Removes extra github requests for each tag by reusing data from the List Releases requests

### PR DESCRIPTION
**Pull request by ddotthomas**
No longer builds a github api request from a release tag. Now using one Github API call to get Download info Cleaned up main.rs; now it parses user data and starts a function Fixed some minor spelling mistakes and other errors

### CODE REVIEW

**Comment by auyer** [comment]
Hi. Thanks ! I will take a a few days look at your PR because I am traveling.

**Comment by auyer** [comment]
Hi, I am only now able to check this PR.
Can you please describe the issues you are trying to fix?
I see you changed a lot of code, and this makes it hard to review this PR.
Also, I could not find an error like you described in the title.

**Comment by ddotthomas** [comment]
First off I moved much of the program out of the main function and into their own respective functions. In doing so I noticed the function github::fetch_data_from_tag is called several times originally in main. I changed the programs logic (which was a lot of code to do, sorry) to only call the github list_releases which already would return all the data from fetch_data_from data but in a large list of each tag/release. I switched to using that one large list which was already in memory/ in the RAM instead of making further web requests to Github.


I can't find the tag/version that caused it now but I think one of the tags from either steam or Lutris would error out saying github couldn't find anything at the requested URL, so I feel that using the data from the one list instead of making further calls also helps the stability of the program and keep potential web/internet errors to a minimum.


I also merged the tag_menu and variants_menu functions in the helper_menus into one multiple_select_menu function which does the same functionality as both by switching the passed in Vec into a Generic Type that implements Display which the AppInstallations and String type both do. 


Most of the large deletions and additions are from moving the download logic out of main and into download.rs. If you read download.rs you should recognize the same functionality that was originally in main.


I also tried to implement some function programming principles, meaning before in main the program would update several bool variables such as 'should_detect_apps' and then run through several if and else statements to parse the user's data. I switched the logic to instead check the user's answer once in the match statement against the 'answer' variable and then run whichever associated function that corresponds or matches that answer. I think this will save the CPU a couple brances when it doesn't have to check if statements that are no longer relevant to what the user is trying to do. For example, if the user wants to open the tag selector, originally the program or CPU would have to check against manage_existing_versions, should_detect_apps and a couple other if statements in order to get to the functionality in the program we actually want in this case. By instead launching the function we want right from the initial match statement we can skip all that and save some resources while achieving the same result.

Let me know if you need me to discuss or explain anything further.

**Comment by auyer** [comment]
Some of these changes I wanted to make too. I agree the main file needed some work.
I will make some tests in your branch now. Thanks!

**Review by auyer — COMMENTED** [review]
I will make one small change to the PR before merging

**Pull request merged**
